/** Brand logo lookup backed by /images/brands/brands.json (generated by scripts/fetch_logos.py). Client-side helper. */
export type BrandLogoEntry = {
  slug: string;
  brand: string;
  category: string;
  logo: string | null;
  status: string;
};

type BrandIndex = { fallback: string; brands: BrandLogoEntry[] };

const DEFAULT_FALLBACK = "/images/placeholder.svg";
let indexPromise: Promise<BrandIndex> | null = null;

export function brandSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[\u2019']/g, "")
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
    .replace(/\s+/g, "-");
}

function loadIndex(): Promise<BrandIndex> {
  if (!indexPromise) {
    indexPromise = fetch("/images/brands/brands.json")
      .then((r) => {
        if (!r.ok) throw new Error(`brands.json ${r.status}`);
        return r.json() as Promise<BrandIndex>;
      })
      .catch(() => {
        indexPromise = null;
        return { fallback: DEFAULT_FALLBACK, brands: [] };
      });
  }
  return indexPromise;
}

/** Returns the brand's logo URL, or the placeholder when the brand or logo is unknown. */
export async function getBrandLogo(brand: string): Promise<string> {
  const index = await loadIndex();
  const hit = index.brands.find((b) => b.slug === brandSlug(brand));
  return hit?.logo ?? index.fallback ?? DEFAULT_FALLBACK;
}
